# Generated by Django 4.2.3 on 2023-09-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='emp',
            new_name='std',
        ),
    ]
