# Generated by Django 4.2.3 on 2023-09-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_emp_std'),
    ]

    operations = [
        migrations.RenameField(
            model_name='std',
            old_name='phone',
            new_name='mobile',
        ),
    ]
